x-jenkins-ssh-agent-definition: &jenkins-ssh-agent-definition
  # https://hub.docker.com/r/jenkins/ssh-agent
  build:
    context: ./jenkins-ssh-agent
  image: jenkins-ssh-agent-image
  expose:
    - "22"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    # jenkins/ssh-agent container automatically registers JENKINS_AGENT_SSH_PUBKEY to `/home/jenkins/.ssh/authorized_keys` on startup
    JENKINS_AGENT_SSH_PUBKEY: ${JENKINS_AGENT_SSH_PUBKEY}
  networks:
    - jenkins-network
  depends_on:
    - jenkins-controller

x-jenkins-inbound-agent-definition: &jenkins-inbound-agent-definition
  # https://hub.docker.com/r/jenkins/inbound-agent
  build:
    context: ./jenkins-inbound-agent
  image: jenkins-inbound-agent-image
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  networks:
    - jenkins-network
  depends_on:
    - jenkins-controller

x-jenkins-inbound-agent-base-environment: &jenkins-inbound-agent-base-environment
  JENKINS_URL: http://jenkins-controller:8080
  JENKINS_AGENT_WORKDIR: /home/jenkins/agent

services:
  jenkins-controller:
    build:
      # https://docs.docker.com/reference/compose-file/build/#context
      context: ./jenkins-controller
    image: jenkins-controller-image
    container_name: jenkins-controller-container
    ports:
      - 8080:8080
      - 50000:50000 # 50000 = jenkins agent connects to controller on 50000 port
    volumes:
      - ./jenkins-controller-data:/var/jenkins_home
      # dood pattern
      # jenkins-controller-container calls api to docker daemon of host machine, via /var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
    user: jenkins
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/login"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - jenkins-network

  jenkins-ssh-agent1:
    <<: *jenkins-ssh-agent-definition
  jenkins-ssh-agent2:
    <<: *jenkins-ssh-agent-definition

  jenkins-inbound-agent1:
    <<: *jenkins-inbound-agent-definition
    environment:
      <<: *jenkins-inbound-agent-base-environment
      # curl -sO http://localhost:8080/jnlpJars/agent.jar java -jar agent.jar -url http://localhost:8080/ -secret JENKINS_INBOUND_AGENT1_SECRET -name JENKINS_INBOUND_AGENT1_NAME -webSocket -workDir "/home/jenkins/agent"
      # You need to specify the same `-secret` and `-name` arguments as the like above command, shown under `Run from agent command line: (Unix)` on the Jenkins Web Console node status page
      JENKINS_SECRET: ${JENKINS_INBOUND_AGENT1_SECRET}
      JENKINS_AGENT_NAME: ${JENKINS_INBOUND_AGENT1_NAME}

networks:
  jenkins-network:
    driver: bridge
