services:
  jenkins-controller:
    build:
      # https://docs.docker.com/reference/compose-file/build/#context
      context: ./jenkins-controller
      dockerfile: Dockerfile
    image: jenkins-controller-image
    container_name: jenkins-controller-container
    ports:
      - 8080:8080
      - 50000:50000 # 50000 = jenkins agent connects to controller on 50000 port
    volumes:
      - ./jenkins-controller-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    user: jenkins
    environment:
      # https://docs.docker.jp/compose/reference/envvars.html#docker-host
      # when jenkins controller executes docker pipeline, it connects to `docker` 2376 port with mTLS.
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    depends_on: 
      - dind-runner

    networks:
      - jenkins-network

  # docker in docker pattern
  dind-runner:
    image: docker:dind
    container_name: jenkins-docker-container
    privileged: true
    expose: 
      - "2376"
    volumes:
      - ./jenkins-controller-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
    environment:
      # https://hub.docker.com/_/docker#tls
      # dind image creates TLS certificates in DOCKER_TLS_CERTDIR
      - DOCKER_TLS_CERTDIR=/certs
    networks:
      jenkins-network:
        aliases:
          - docker # for DOCKER_HOST=tcp://docker:2376 name resolver

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins-docker-certs:
