services:
  jenkins-controller:
    build:
      # https://docs.docker.com/reference/compose-file/build/#context
      context: ./jenkins-controller
      dockerfile: Dockerfile # [context = ./jenkins-controller]/Dockerfile
    image: jenkins-controller-image
    container_name: jenkins-controller-container
    ports:
      # 8081 = your pc port, 8080 = jenkins-controller port in container
      - 8081:8080
      # 50000 = jenkins agent node connects to the controller on 50000 port
      - 50000:50000
    volumes:
      - ./jenkins-controller-data:/var/jenkins_home
      # When the jenkins controller attempts to execute a docker pipeline, use the docker daemon running on the host PC.
      - /var/run/docker.sock:/var/run/docker.sock
    user: jenkins

    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge
